name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
    - name: Set up JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - name: Publish with Gradle
      run: ./gradlew -Pgpr.key=${{ secrets.GITHUB_TOKEN }} publish